### ISSUE TITLE
Reference "level of git" from centralized collaborative workflow?

### ISSUE THREAD

**Issue by juholehtonen** [coderefinery/git-collaborative#100]
Would it be useful to reference the level of git lesson https://coderefinery.github.io/git-intro/14-level/ from "Collaborative distributed version control: Working with remotes and centralized workflow" (https://github.com/coderefinery/git-collaborative/blame/gh-pages/_episodes/01-remotes.md#L250)?

**Comment by wikfeldt** [comment]
i think git-collab episode 1 has evolved since this issue was opened, and i can't think of a natural way to link to the "how much git is necessary" git-intro episode. We clearly emphasize the importance of using feature branches in the centralized and forking exercises so the points raised in https://coderefinery.github.io/git-intro/14-level/ are mostly covered. Closing the issue for now

**Comment by wikfeldt** [comment]
reopening since i found a place for this
