### ISSUE TITLE
Make it possible to host a spin-off workshop without us doing anything

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#57]

**Comment by bast** [comment]
Currently this is not possible (repositories require us to rewind them and activate them, the lessons are centralized, we need to decentralize them)

**Comment by bast** [comment]
I am considering using the GitHub importer to set up exercise repositories: https://github.com/new/import

**Comment by annefou** [comment]
It is a very good idea. For the workshop in Oslo (Git in practice), I did not use the coderefinery organization and I used CodeRefinery repositories  to get a copy in my own github username (import is best).  It requires a few updates in the lesson (where attendees do not clone coderefinery repo but mine) and in the instructions (especially to set up collaboration with git) otherwise it is a great approach.

**Comment by bast** [comment]
I consider this now done.
